# https://zenn.dev/kariya_mitsuru/articles/e226e2440a849c
set-option default-terminal tmux-256color
set-option -a terminal-overrides $TERM:RGB

# prefixキーの変更
unbind C-b
set -g prefix C-q

# PaneをVim-likeに移動する
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

bind -r | split-window -h -c "#{pane_current_path}"
bind -r - split-window -v -c "#{pane_current_path}"

# tmuxの操作をviキーバインドにする
set-window-option -g mode-keys vi

# ステータスラインの設定
set-option -g status-left "[#{active_window_index}] "
set-option -g status-right '%m/%d[%a] %H:%M'
# ウィンドウステータスの設定
set-option -g window-status-separator " | "
set-option -g window-status-current-format '#(
  label="#I:#W*"; \
  echo "#[bold]$label#[default]"
)'

# コピーモードの設定
set-option -s set-clipboard on
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi V send-keys -X select-line
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-pipe

# プラグインの有効化
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
# セッションの永続化
# <prefix><Ctrl-s>で保存
# <prefix><Ctrl-r>で復元
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
