require("base")
require("init_lazy")

require("config.color-schema")
require("config.finder")
require("config.tabs")
require("config.indent")
require("config.filer")
require("config.terminal")
require("config.git")
require("config.mini")
require("config.lsp")
